_wandb:
    value:
        cli_version: 0.25.1
        e:
            3idlc7cesrg61hm7l7w23j8cp6ebws3t:
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "121018208256"
                        used: "111425933312"
                email: tetefalcao.18@gmail.com
                executable: /Users/tete/TPS/projet_pytorch/venv/bin/python
                git:
                    commit: 46dea0da9b0c62c972f3bfa13341a6b514bf6e53
                    remote: https://github.com/cmacquartmoulin-pixel/projet_pytorch.git
                host: MacBook-Air-de-Ana-7.local
                memory:
                    total: "8589934592"
                os: macOS-14.8.4-x86_64-i386-64bit
                program: /Users/tete/TPS/projet_pytorch/src/train.py
                python: CPython 3.12.7
                root: /Users/tete/TPS/projet_pytorch
                startedAt: "2026-03-26T09:28:01.472350Z"
                writerId: 3idlc7cesrg61hm7l7w23j8cp6ebws3t
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 1
                - 13
                - 16
            "4": 3.12.7
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-x86_64
augmentation:
    value:
        enabled: true
        name: random_crop
        padding: 4
        size: 32
batch_size:
    value: 32
cnn_activation:
    value:
        activation:
            _target_: torch.nn.ReLU
            inplace: true
        name: relu
cnn_init:
    value:
        gain: 1
        type: xavier
debug:
    value: true
debug_size:
    value: 1000
early_stopping:
    value:
        enabled: true
        min_delta: 0.001
        patience: 5
epochs:
    value: 30
loss:
    value:
        _target_: torch.nn.CrossEntropyLoss
mlp_activation:
    value:
        activation:
            _target_: torch.nn.ReLU
            inplace: true
        name: relu
mlp_init:
    value:
        gain: 1
        type: xavier
model:
    value:
        cnn:
            in_channels: 3
            kernel_size: 3
            name: simple
            out_channels:
                - 32
                - 64
            padding: 1
            pool: 2
            stride: 1
        mlp:
            dropout: 0.5
            mlp_dims:
                - 4096
                - 512
                - 128
                - 10
            name: classifier
optimizer:
    value:
        _target_: torch.optim.Adam
        betas:
            - 0.9
            - 0.999
        lr: 0.001888
seed:
    value: 42
