# -------------------------------
# conf/config.yaml
# -------------------------------
defaults:
  - model/mlp: classifier
  - model/cnn: simple
  - activation@cnn_activation : relu    # activation par défaut du CNN
  - activation@mlp_activation : relu    # activation par défaut du MLP
  - init@cnn_init             : xavier  # initialisation par défaut du CNN
  - init@mlp_init             : xavier  # initialisation par défaut du MLP  
  - optimizer: adam
  - loss: cross_entropy
  - _self_  
  # - scheduler: step  

seed: 42
epochs: 10
batch_size: 32

#
debug: true        # ← flag debug
debug_size: 1000   # ← taille du sous-ensemble