# -------------------------------
# conf/config.yaml
# -------------------------------
defaults:
  - model/mlp: classifier
  - model/cnn: simple
  - activation@cnn_activation : relu    # activation par défaut du CNN
  - activation@mlp_activation : relu    # activation par défaut du MLP
  - init@cnn_init             : xavier  # initialisation par défaut du CNN
  - init@mlp_init             : xavier  # initialisation par défaut du MLP  
  - optimizer: adam
  - loss: cross_entropy
  - augmentation: default 
  - _self_

seed: 42
epochs: 30
batch_size: 32

early_stopping:
  enabled: true
  patience: 5
  min_delta: 0.001

debug: true
debug_size: 1000