_wandb:
    value:
        cli_version: 0.24.2
        e:
            f4hvxi906vek3o4yh8yb2xr19bagaoky:
                codePath: src\train.py
                codePathLocal: train.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "125739986944"
                        used: "110719737856"
                email: cmacquartmoulin@gmail.com
                executable: C:\Users\Clémence\Documents\Projet Python (porg II)\.venv\Scripts\python.exe
                git:
                    commit: 9487ef3f20ac5f0c6c2331a9d153ce0d1d3f799c
                    remote: https://github.com/cmacquartmoulin-pixel/projet_pytorch
                host: DESKTOP-150MSDQ
                memory:
                    total: "4207968256"
                os: Windows-10-10.0.19041-SP0
                program: train.py
                python: CPython 3.8.6
                root: C:\Users\Clémence\Documents\Projet Python (porg II)\src
                startedAt: "2026-04-01T08:13:48.344493Z"
                writerId: f4hvxi906vek3o4yh8yb2xr19bagaoky
        m: []
        python_version: 3.8.6
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 1
                - 2
                - 3
                - 13
                - 16
            "4": 3.8.6
            "5": 0.24.2
            "8":
                - 3
            "12": 0.24.2
            "13": windows-amd64
augmentation:
    value:
        horizontal_flip:
            enabled: true
            name: horizontal_flip
        random_crop:
            enabled: true
            name: random_crop
            padding: 4
            size: 32
batch_size:
    value: 32
cnn_activation:
    value:
        activation:
            _target_: torch.nn.ReLU
            inplace: true
        name: relu
cnn_init:
    value:
        gain: 1
        type: xavier
debug:
    value: true
debug_size:
    value: 500
early_stopping:
    value:
        enabled: true
        min_delta: 0.0005
        patience: 10
epochs:
    value: 12
loss:
    value:
        _target_: torch.nn.CrossEntropyLoss
mlp_activation:
    value:
        activation:
            _target_: torch.nn.ReLU
            inplace: true
        name: relu
mlp_init:
    value:
        gain: 1
        type: xavier
model:
    value:
        cnn:
            in_channels: 3
            kernel_size: 3
            name: simple
            out_channels:
                - 32
                - 64
            padding: 1
            pool: 2
            stride: 1
        mlp:
            dropout: 0.5
            mlp_dims:
                - 4096
                - 512
                - 128
                - 10
            name: classifier
optimizer:
    value:
        _target_: torch.optim.SGD
        lr: 0.0001
        momentum: 0.9
        weight_decay: 0.0001
scheduler:
    value:
        _target_: torch.optim.lr_scheduler.StepLR
        gamma: 0.1
        step_size: 5
seed:
    value: 42
