# -------------------------------
# conf/model/optimizer/adam.yaml
# -------------------------------

_name_: adam
_target_: torch.optim.Adam 
lr: 0.001   # initial learning rate
betas: [0.9, 0.999] # Coefficients used for computing running averages of gradient and its square

#0.9 -> how much the optimizer relies on the past gradients (momentum)
#0.999 -> how much the optimizer relies on the past squared gradients (RMSProp)